-- MySQL Script generated by MySQL Workbench
-- Fri Feb 20 11:30:33 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Autores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autores` (
  `idAutores` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Libros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Libros` (
  `idLibros` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `año_publi` INT NULL,
  `categoria` VARCHAR(45) NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idLibros`, `Usuarios_idUsuarios`),
  INDEX `fk_Libros_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libros_has_Autores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Libros_has_Autores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Libros_has_Autores` (
  `Libros_idLibros` INT NOT NULL,
  `Autores_idAutores` INT NOT NULL,
  PRIMARY KEY (`Libros_idLibros`, `Autores_idAutores`),
  INDEX `fk_Libros_has_Autores_Autores1_idx` (`Autores_idAutores` ASC) VISIBLE,
  INDEX `fk_Libros_has_Autores_Libros_idx` (`Libros_idLibros` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_has_Autores_Libros`
    FOREIGN KEY (`Libros_idLibros`)
    REFERENCES `mydb`.`Libros` (`idLibros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_has_Autores_Autores1`
    FOREIGN KEY (`Autores_idAutores`)
    REFERENCES `mydb`.`Autores` (`idAutores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Préstamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Préstamos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Préstamos` (
  `Préstamos_Usuarios_idUsuarios` INT NOT NULL,
  `Libros_idLibros` INT NOT NULL,
  `Libros_Usuarios_idUsuarios` INT NOT NULL,
  `fecha_prestamo` DATE NULL,
  `fecha_dev` DATE NULL,
  PRIMARY KEY (`Préstamos_Usuarios_idUsuarios`, `Libros_idLibros`, `Libros_Usuarios_idUsuarios`),
  INDEX `fk_Préstamos_has_Libros_Libros1_idx` (`Libros_idLibros` ASC, `Libros_Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Préstamos_has_Libros_Libros1`
    FOREIGN KEY (`Libros_idLibros` , `Libros_Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Libros` (`idLibros` , `Usuarios_idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `fecha_reg` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
