-- MySQL Script generated by MySQL Workbench
-- Mon Feb 23 11:02:01 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tienda_zapatillas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tienda_zapatillas` ;

-- -----------------------------------------------------
-- Schema tienda_zapatillas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda_zapatillas` DEFAULT CHARACTER SET utf8 ;
USE `tienda_zapatillas` ;

-- -----------------------------------------------------
-- Table `tienda_zapatillas`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_zapatillas`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `tienda_zapatillas`.`Clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `numero_telefono` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_zapatillas`.`Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_zapatillas`.`Empleados` ;

CREATE TABLE IF NOT EXISTS `tienda_zapatillas`.`Empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tienda` VARCHAR(45) NOT NULL,
  `salario` INT NULL,
  `fecha_incorporacion` DATE NOT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_zapatillas`.`Facturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_zapatillas`.`Facturas` ;

CREATE TABLE IF NOT EXISTS `tienda_zapatillas`.`Facturas` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `num_factura` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `id_zapatilla` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `id_zapatilla_idx` (`id_zapatilla` ASC) VISIBLE,
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `id_zapatilla`
    FOREIGN KEY (`id_zapatilla`)
    REFERENCES `tienda_zapatillas`.`Zapatillas` (`id_zapatillas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `tienda_zapatillas`.`Empleados` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `tienda_zapatillas`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_zapatillas`.`Zapatillas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_zapatillas`.`Zapatillas` ;

CREATE TABLE IF NOT EXISTS `tienda_zapatillas`.`Zapatillas` (
  `id_zapatillas` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_zapatillas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
